### ISSUE TITLE
The control is too raw yet

### ISSUE THREAD

**Issue by Gargo** [ayman-ibrahim/ProcessLoadingView#2]
you peg it as something like "progress view". Ok, could you provide a clear way how to set the progress. In other controls you just set one variable from 0 to 100 percent and progress redraws by itself. But not in your case

**Comment by ayman-ibrahim** [comment]
@Gargo 
The processLoadingView does not set it's progress through percentage from 0 to 100 %,
Otherwise it's step based, as you should set the step completed:
options.stepComplete = stepComplete

I added a new section in the readme showing how setup the view called > Fast Setup.

**Comment by Gargo** [comment]
@ayman-ibrahim ok, setting of `options.stepComplete` just sets this variable.

Tried to press "reset" after changes - the lines become blue but it doesn't affect the circle images.

For example in your example you set 3 of 8 steps completed. What should I do to set all 8 steps completed?

**Comment by ayman-ibrahim** [comment]
@Gargo 
Simply you set:
```
stepComplete = 8
options.stepComplete = stepComplete
```

The reseting button is calling this method:
`viewProcess.reverse(removeBtns: true, completed: nil)`
Which only resets the drawing.

If you wish to make the steps completed:
replace the reset action method in the demo with:

```
@IBAction func reset(_ sender: Any)
    {
        viewProcess.reverse(removeBtns: true, completed:
        {
            self.options.mainText = "Finished"
            self.options.subText = "DONE"
            self.options.images = self.imageOpts(of: 8, totalSteps: 8)
            self.viewProcess.start()
        })
    }
```
