### ISSUE TITLE
Impossible to add to a project ..

### ISSUE THREAD

**Issue by AntoineWaes** [ayman-ibrahim/ProcessLoadingView#3]
I used cocoapods,
Then I add a view, class ProcessLoadingView
Then, import ProcessLoadingView
Then,  @IBOutlet var viewProcess: ProcessLoadingView!

and I still having this error : "Use of undeclared type 'ProcessLoadingView'"

I can't fix it, please help me

Thanks

**Comment by ayman-ibrahim** [comment]
Hello @AntoineWaes ,

Just update your pod file to:
pod 'ProcessLoadingView', '~> 0.1.1'
And reinstall it, and it will work fine.
