### ISSUE TITLE
Crashing When displaying on screen

### ISSUE THREAD

**Issue by Esko918** [ayman-ibrahim/ProcessLoadingView#4]
Im displaying the view programmatically in one of my views as a progress indicator for when data is being downloaded. When I display the view the code keeps crashing on this line  textLayerParent.position = self.myCenter in the preparation method. Any idea why?

**Comment by Esko918** [comment]
Fatal error: Unexpectedly found nil while unwrapping an Optional value
This is the error

**Comment by ayman-ibrahim** [comment]
Hello @Esko918 
The problem is that `self.myCenter` is not set as `layoutSubviews()` most probably not being called
can you show me, how are you adding the view programmatically ?

**Comment by Esko918** [comment]
Sorry I cant. We ended up using a different module for this and I don't remember what I wrote as the code. But its probably just what you suggested in your git hub since I know I couldn't get it passed this issue. It could have been an iOS 10.x issue also since I know throughout this whole project iOS 10 was making certain code act a lot differently than in iOS 9 and 11
